# Generated by Django 5.1.3 on 2025-03-23 06:21

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'amenities',
            },
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.IntegerField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('area_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='area_image')),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='Room', max_length=100)),
                ('room_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('room_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('room_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='room_image')),
                ('description', models.TextField(blank=True)),
                ('capacity', models.TextField(max_length=100)),
                ('amenities', models.ManyToManyField(blank=True, related_name='rooms', to='property.amenities')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
