# Generated by Django 5.1.7 on 2025-03-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
