# Generated by Django 5.1.7 on 2025-03-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('guest', 'Guest')], default='guest', max_length=20),
        ),
    ]
