# Generated by Django 5.1.7 on 2025-03-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0002_alter_customusers_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='customusers',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('guest', 'Guest')], default='guest', max_length=20),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
